### ISSUE TITLE
Miner support.

### ISSUE THREAD

**Issue by itsmylife44** [felixbrucker/miner-monitor#1]
Hi. 

What for miner is  supported? 
Ive try claymore buts not working.

**Comment by chitkiu** [comment]
![image](https://user-images.githubusercontent.com/10129411/36443473-8a8262a0-1681-11e8-9f1d-9f08ec5fbc43.png)
Support

**Comment by itsmylife44** [comment]
How  do you  set the api of claymore ?

**Comment by chitkiu** [comment]
You installed miner-manager?

**Comment by felixbrucker** [comment]
@itsmylife44 as @chitkiu pointed out you cant directly monitor claymore miners with miner-monitor, you will need to run miner-manager agent on the rigs you want to monitor
