### ISSUE TITLE
MPH API not responding

### ISSUE THREAD

**Issue by vapor99** [felixbrucker/miner-monitor#2]
I double checked my API key/username and get the following from npm.

[2018-03-21 11:51:02] [MPH :: Miningpoolhub-API] => Request failed with status code 401

Not sure what is causing this but this API key/username works with all other software I use.

**Comment by felixbrucker** [comment]
username is not required, however the user id is required

it can be obtained here: https://miningpoolhub.com/?page=account&action=edit
